// This file is automatically generated by `scripts/generate-validators`. Do not edit directly.

import { createValidator } from 'lib/server/api';

export default createValidator({
	$schema: 'http://json-schema.org/draft-07/schema#',
	$ref: '#/definitions/RequestMethod',
	definitions: {
		RequestMethod: {
			type: 'string',
			enum: [
				'GET',
				'PATCH'
			]
		}
	}
}, {
	$schema: 'http://json-schema.org/draft-07/schema#',
	$ref: '#/definitions/Request',
	definitions: {
		'Request': {
			anyOf: [
				{
					type: 'object',
					additionalProperties: false,
					properties: {
						body: {},
						query: {
							type: 'object',
							properties: {
								storyID: {
									type: 'string'
								}
							},
							required: [
								'storyID'
							],
							additionalProperties: false
						},
						method: {
							type: 'string',
							const: 'GET'
						}
					},
					required: [
						'method',
						'query'
					]
				},
				{
					type: 'object',
					additionalProperties: false,
					properties: {
						body: {
							$ref: '#/definitions/RecursivePartial%3C(alias-731470504-70263-70404-731470504-0-212510%3Cdef-alias-909996108-538-886-909996108-0-22051254867758%2Calias-295474462-754-1075-295474462-0-5496179474025%3E%26structure-295474462-1250-1411-295474462-1212-1411-295474462-1194-1412-295474462-1186-1412-295474462-1165-1415-295474462-1141-1415-295474462-1139-1417-295474462-1103-1417-295474462-1091-1513-295474462-1082-5470-295474462-1075-5470-295474462-1075-5471-295474462-0-5496)%3E'
						},
						query: {
							type: 'object',
							properties: {
								storyID: {
									type: 'string'
								}
							},
							required: [
								'storyID'
							],
							additionalProperties: false
						},
						method: {
							type: 'string',
							const: 'PATCH'
						}
					},
					required: [
						'body',
						'method',
						'query'
					]
				}
			]
		},
		'RecursivePartial<(alias-731470504-70263-70404-731470504-0-212510<def-alias-909996108-538-886-909996108-0-22051254867758,alias-295474462-754-1075-295474462-0-5496179474025>&structure-295474462-1250-1411-295474462-1212-1411-295474462-1194-1412-295474462-1186-1412-295474462-1165-1415-295474462-1141-1415-295474462-1139-1417-295474462-1103-1417-295474462-1091-1513-295474462-1082-5470-295474462-1075-5470-295474462-1075-5471-295474462-0-5496)>': {
			type: 'object',
			properties: {
				title: {
					type: 'string',
					minLength: 1,
					maxLength: 50
				},
				status: {
					type: 'number',
					enum: [
						0,
						1,
						2,
						3
					]
				},
				privacy: {
					type: 'number',
					enum: [
						0,
						1,
						2
					]
				},
				owner: {
					type: 'string'
				},
				editors: {
					type: 'array',
					items: {
						type: 'string'
					}
				},
				author: {
					$ref: '#/definitions/RecursivePartial%3C(structure-1607858492-2951-2995-1607858492-2941-2996-1607858492-1972-3818-1607858492-1832-3819-1607858492-0-16831%7Cundefined)%3E'
				},
				description: {
					type: 'string',
					maxLength: 2000
				},
				icon: {
					anyOf: [
						{
							type: 'string',
							const: ''
						},
						{
							$ref: '#/definitions/URLString'
						}
					]
				},
				banner: {
					anyOf: [
						{
							type: 'string',
							const: ''
						},
						{
							$ref: '#/definitions/URLString'
						}
					]
				},
				style: {
					type: 'string'
				},
				tags: {
					type: 'array',
					items: {
						$ref: '#/definitions/TagString'
					},
					uniqueItems: true,
					maxItems: 50
				},
				allowComments: {
					type: 'boolean'
				},
				sidebarContent: {
					type: 'string',
					maxLength: 2000
				},
				defaultPageTitle: {
					type: 'string',
					maxLength: 500
				},
				willDelete: {
					type: 'boolean'
				},
				anniversary: {
					$ref: '#/definitions/RecursivePartial%3Cindexed-type-731470504-70377-70403-731470504-70263-70404-731470504-0-212510%3Cstructure-1607858492-2288-2634-1607858492-2145-2635-1607858492-1972-3818-1607858492-1832-3819-1607858492-0-16831%2C(%22year%22%7C%22month%22%7C%22day%22)%3E%3E'
				},
				script: {
					$ref: '#/definitions/RecursivePartial%3Cindexed-type-731470504-70377-70403-731470504-70263-70404-731470504-0-212510%3Cstructure-1607858492-3370-3416-1607858492-3361-3417-1607858492-1972-3818-1607858492-1832-3819-1607858492-0-16831%2C%22unverified%22%3E%3E'
				}
			},
			additionalProperties: false
		},
		'RecursivePartial<(structure-1607858492-2951-2995-1607858492-2941-2996-1607858492-1972-3818-1607858492-1832-3819-1607858492-0-16831|undefined)>': {
			type: 'object',
			properties: {
				name: {
					type: 'string'
				},
				site: {
					anyOf: [
						{
							type: 'string',
							const: ''
						},
						{
							$ref: '#/definitions/URLString'
						}
					]
				}
			},
			additionalProperties: false
		},
		'URLString': {
			type: 'string',
			pattern: '^https?://'
		},
		'TagString': {
			type: 'string',
			minLength: 1,
			maxLength: 50,
			pattern: '^[a-z0-9](?:[a-z0-9-]*[a-z0-9])?$'
		},
		'RecursivePartial<indexed-type-731470504-70377-70403-731470504-70263-70404-731470504-0-212510<structure-1607858492-2288-2634-1607858492-2145-2635-1607858492-1972-3818-1607858492-1832-3819-1607858492-0-16831,("year"|"month"|"day")>>': {
			type: 'object',
			properties: {
				year: {
					$ref: '#/definitions/integer'
				},
				month: {
					$ref: '#/definitions/integer',
					minimum: 0,
					maximum: 11
				},
				day: {
					$ref: '#/definitions/integer',
					description: 'The anniversary\'s day of the month.',
					minimum: 1
				}
			},
			additionalProperties: false
		},
		'integer': {
			type: 'integer'
		},
		'RecursivePartial<indexed-type-731470504-70377-70403-731470504-70263-70404-731470504-0-212510<structure-1607858492-3370-3416-1607858492-3361-3417-1607858492-1972-3818-1607858492-1832-3819-1607858492-0-16831,"unverified">>': {
			type: 'object',
			properties: {
				unverified: {
					type: 'string'
				}
			},
			additionalProperties: false
		}
	}
});