// This file is automatically generated by `scripts/generate-validators`. Do not edit directly.

import { createValidator } from 'modules/server/api';

export default createValidator({
	$schema: 'http://json-schema.org/draft-07/schema#',
	$ref: '#/definitions/RequestMethod',
	definitions: {
		RequestMethod: {
			type: 'string',
			enum: [
				'GET',
				'PUT'
			]
		}
	}
}, {
	$schema: 'http://json-schema.org/draft-07/schema#',
	$ref: '#/definitions/Request',
	definitions: {
		'Request': {
			anyOf: [
				{
					type: 'object',
					additionalProperties: false,
					properties: {
						body: {},
						query: {
							type: 'object',
							properties: {
								storyID: {
									type: 'string'
								}
							},
							required: [
								'storyID'
							],
							additionalProperties: false
						},
						method: {
							type: 'string',
							const: 'GET'
						}
					},
					required: [
						'method',
						'query'
					]
				},
				{
					type: 'object',
					additionalProperties: false,
					properties: {
						body: {
							$ref: '#/definitions/RecursivePartial%3C(alias-2073358172-70263-70404-2073358172-0-212357%3Cdef-alias--1089-1419--0-27751254867758%2Calias--801-1132--0-5358357827294%3E%26structure--1305-1466--1267-1466--1249-1467--1241-1467--1222-1470--1198-1470--1196-1472--1160-1472--1148-1566--1139-5332--1132-5332--1132-5333--0-5358)%3E'
						},
						query: {
							type: 'object',
							properties: {
								storyID: {
									type: 'string'
								}
							},
							required: [
								'storyID'
							],
							additionalProperties: false
						},
						method: {
							type: 'string',
							const: 'PUT'
						}
					},
					required: [
						'body',
						'method',
						'query'
					]
				}
			]
		},
		'RecursivePartial<(alias-2073358172-70263-70404-2073358172-0-212357<def-alias--1089-1419--0-27751254867758,alias--801-1132--0-5358357827294>&structure--1305-1466--1267-1466--1249-1467--1241-1467--1222-1470--1198-1470--1196-1472--1160-1472--1148-1566--1139-5332--1132-5332--1132-5333--0-5358)>': {
			type: 'object',
			properties: {
				title: {
					type: 'string',
					minLength: 1,
					maxLength: 50
				},
				status: {
					$ref: '#/definitions/StoryStatus'
				},
				privacy: {
					$ref: '#/definitions/StoryPrivacy'
				},
				owner: {
					type: 'string'
				},
				editors: {
					type: 'array',
					items: {
						type: 'string'
					}
				},
				author: {
					$ref: '#/definitions/RecursivePartial%3C(structure--2937-2981--2927-2982--1958-3720--1818-3721--0-16882%7Cundefined)%3E'
				},
				description: {
					type: 'string',
					maxLength: 2000
				},
				blurb: {
					type: 'string',
					maxLength: 500
				},
				icon: {
					anyOf: [
						{
							type: 'string',
							const: ''
						},
						{
							$ref: '#/definitions/URLString'
						}
					]
				},
				banner: {
					anyOf: [
						{
							type: 'string',
							const: ''
						},
						{
							$ref: '#/definitions/URLString'
						}
					]
				},
				style: {
					type: 'string'
				},
				disableUserTheme: {
					type: 'boolean',
					description: 'Whether the story should ignore the reader\'s theme setting.'
				},
				tags: {
					type: 'array',
					items: {
						$ref: '#/definitions/TagString'
					},
					uniqueItems: true,
					maxItems: 50
				},
				allowComments: {
					type: 'boolean'
				},
				defaultPageTitle: {
					type: 'string',
					maxLength: 500
				},
				willDelete: {
					type: 'boolean'
				},
				anniversary: {
					$ref: '#/definitions/RecursivePartial%3Cindexed-type-2073358172-70377-70403-2073358172-70263-70404-2073358172-0-212357%3Cstructure--2274-2620--2131-2621--1958-3720--1818-3721--0-16882%2C(%22year%22%7C%22month%22%7C%22day%22)%3E%3E'
				},
				script: {
					$ref: '#/definitions/RecursivePartial%3Cindexed-type-2073358172-70377-70403-2073358172-70263-70404-2073358172-0-212357%3Cstructure--3458-3504--3449-3505--1958-3720--1818-3721--0-16882%2C%22unverified%22%3E%3E'
				}
			},
			additionalProperties: false
		},
		'StoryStatus': {
			type: 'number',
			enum: [
				0,
				1,
				2,
				3
			]
		},
		'StoryPrivacy': {
			type: 'number',
			enum: [
				0,
				1,
				2
			]
		},
		'RecursivePartial<(structure--2937-2981--2927-2982--1958-3720--1818-3721--0-16882|undefined)>': {
			type: 'object',
			properties: {
				name: {
					type: 'string'
				},
				site: {
					anyOf: [
						{
							type: 'string',
							const: ''
						},
						{
							$ref: '#/definitions/URLString'
						}
					]
				}
			},
			additionalProperties: false
		},
		'URLString': {
			type: 'string',
			pattern: '^https?://'
		},
		'TagString': {
			type: 'string',
			minLength: 1,
			maxLength: 50,
			pattern: '^[a-z0-9](?:[a-z0-9-]*[a-z0-9])?$'
		},
		'RecursivePartial<indexed-type-2073358172-70377-70403-2073358172-70263-70404-2073358172-0-212357<structure--2274-2620--2131-2621--1958-3720--1818-3721--0-16882,("year"|"month"|"day")>>': {
			type: 'object',
			properties: {
				year: {
					$ref: '#/definitions/integer'
				},
				month: {
					$ref: '#/definitions/integer',
					minimum: 0,
					maximum: 11
				},
				day: {
					$ref: '#/definitions/integer',
					description: 'The anniversary\'s day of the month.',
					minimum: 1
				}
			},
			additionalProperties: false
		},
		'integer': {
			type: 'integer'
		},
		'RecursivePartial<indexed-type-2073358172-70377-70403-2073358172-70263-70404-2073358172-0-212357<structure--3458-3504--3449-3505--1958-3720--1818-3721--0-16882,"unverified">>': {
			type: 'object',
			properties: {
				unverified: {
					type: 'string'
				}
			},
			additionalProperties: false
		}
	}
});