// This file is automatically generated by `scripts/generate-validators`. Do not edit directly.

import { createValidator } from 'lib/server/api';

export default createValidator({
	$schema: 'http://json-schema.org/draft-07/schema#',
	$ref: '#/definitions/RequestMethod',
	definitions: {
		RequestMethod: {
			type: 'string',
			enum: [
				'GET',
				'DELETE',
				'PATCH'
			]
		}
	}
}, {
	$schema: 'http://json-schema.org/draft-07/schema#',
	$ref: '#/definitions/Request',
	definitions: {
		'Request': {
			anyOf: [
				{
					type: 'object',
					additionalProperties: false,
					properties: {
						body: {},
						query: {
							type: 'object',
							properties: {
								storyID: {
									type: 'string'
								},
								newsPostID: {
									type: 'string'
								}
							},
							required: [
								'storyID',
								'newsPostID'
							],
							additionalProperties: false
						},
						method: {
							type: 'string',
							const: 'GET'
						}
					},
					required: [
						'method',
						'query'
					]
				},
				{
					type: 'object',
					additionalProperties: false,
					properties: {
						body: {},
						query: {
							type: 'object',
							properties: {
								storyID: {
									type: 'string'
								},
								newsPostID: {
									type: 'string'
								}
							},
							required: [
								'storyID',
								'newsPostID'
							],
							additionalProperties: false
						},
						method: {
							type: 'string',
							const: 'DELETE'
						}
					},
					required: [
						'method',
						'query'
					]
				},
				{
					type: 'object',
					additionalProperties: false,
					properties: {
						body: {
							$ref: '#/definitions/RecursivePartial%3Calias-731470504-70263-70404-731470504-0-212510%3Cdef-alias--244-510--0-510572081278%2Calias-stID%5D_index.ts-551-713-stID%5D_index.ts-0-33431334727229%3E%3E'
						},
						query: {
							type: 'object',
							properties: {
								storyID: {
									type: 'string'
								},
								newsPostID: {
									type: 'string'
								}
							},
							required: [
								'storyID',
								'newsPostID'
							],
							additionalProperties: false
						},
						method: {
							type: 'string',
							const: 'PATCH'
						}
					},
					required: [
						'body',
						'method',
						'query'
					]
				}
			]
		},
		'RecursivePartial<alias-731470504-70263-70404-731470504-0-212510<def-alias--244-510--0-510572081278,alias-stID]_index.ts-551-713-stID]_index.ts-0-33431334727229>>': {
			type: 'object',
			properties: {
				content: {
					type: 'string',
					minLength: 1,
					maxLength: 20000
				}
			},
			additionalProperties: false
		}
	}
});