// This file is automatically generated by `scripts/generate-validators`. Do not edit directly.

import createAPIValidator from 'lib/server/api/createAPIValidator';

export default createAPIValidator({
	$schema: 'http://json-schema.org/draft-07/schema#',
	$ref: '#/definitions/RequestMethod',
	definitions: {
		RequestMethod: {
			type: 'string',
			enum: [
				'GET',
				'POST'
			]
		}
	}
}, {
	$schema: 'http://json-schema.org/draft-07/schema#',
	$ref: '#/definitions/Request',
	definitions: {
		Request: {
			anyOf: [
				{
					type: 'object',
					additionalProperties: false,
					properties: {
						body: {},
						query: {
							type: 'object',
							properties: {
								userID: {
									type: 'string'
								},
								type: {
									type: 'string',
									enum: [
										'google',
										'discord',
										'password'
									]
								}
							},
							required: [
								'userID'
							],
							additionalProperties: false
						},
						method: {
							type: 'string',
							const: 'GET'
						}
					},
					required: [
						'method',
						'query'
					]
				},
				{
					type: 'object',
					additionalProperties: false,
					properties: {
						body: {
							$ref: '#/definitions/AuthMethodOptions'
						},
						query: {
							type: 'object',
							properties: {
								userID: {
									type: 'string'
								},
								type: {
									type: 'string',
									enum: [
										'google',
										'discord',
										'password'
									]
								}
							},
							required: [
								'userID'
							],
							additionalProperties: false
						},
						method: {
							type: 'string',
							const: 'POST'
						}
					},
					required: [
						'body',
						'method',
						'query'
					]
				}
			]
		},
		AuthMethodOptions: {
			anyOf: [
				{
					$ref: '#/definitions/InternalAuthMethodOptions'
				},
				{
					$ref: '#/definitions/ExternalAuthMethodOptions'
				}
			]
		},
		InternalAuthMethodOptions: {
			type: 'object',
			properties: {
				type: {
					type: 'string',
					const: 'password'
				},
				value: {
					$ref: '#/definitions/PasswordString'
				}
			},
			required: [
				'type',
				'value'
			],
			additionalProperties: false
		},
		PasswordString: {
			type: 'string',
			minLength: 8
		},
		ExternalAuthMethodOptions: {
			type: 'object',
			properties: {
				type: {
					type: 'string',
					enum: [
						'google',
						'discord'
					]
				},
				value: {
					type: 'string',
					minLength: 1
				}
			},
			required: [
				'type',
				'value'
			],
			additionalProperties: false
		}
	}
});