// This file is automatically generated by `scripts/generate-validators`. Do not edit directly.

import createAPIValidator from 'lib/server/api/createAPIValidator';

export default createAPIValidator({
	$schema: 'http://json-schema.org/draft-07/schema#',
	$ref: '#/definitions/RequestMethod',
	definitions: {
		RequestMethod: {
			type: 'string',
			const: 'POST'
		}
	}
}, {
	$schema: 'http://json-schema.org/draft-07/schema#',
	$ref: '#/definitions/Request',
	definitions: {
		Request: {
			type: 'object',
			additionalProperties: false,
			properties: {
				body: {
					type: 'object',
					properties: {
						title: {
							type: 'string',
							minLength: 1,
							maxLength: 50
						}
					},
					required: [
						'title'
					],
					additionalProperties: false
				},
				query: {},
				method: {
					type: 'string',
					const: 'POST'
				}
			},
			required: [
				'body',
				'method'
			]
		}
	}
});