// This file is automatically generated by `scripts/generate-validators`. Do not edit directly.

import { createValidator } from 'modules/server/api';

export default createValidator({
	$schema: 'http://json-schema.org/draft-07/schema#',
	$ref: '#/definitions/RequestMethod',
	definitions: {
		RequestMethod: {
			type: 'string',
			enum: [
				'DELETE',
				'PUT'
			]
		}
	}
}, {
	$schema: 'http://json-schema.org/draft-07/schema#',
	$ref: '#/definitions/Request',
	definitions: {
		'Request': {
			anyOf: [
				{
					type: 'object',
					additionalProperties: false,
					properties: {
						body: {},
						method: {
							type: 'string',
							const: 'DELETE'
						}
					},
					required: [
						'method'
					]
				},
				{
					type: 'object',
					additionalProperties: false,
					properties: {
						body: {
							$ref: '#/definitions/RecursivePartial%3Calias-731470504-70254-70395-731470504-0-212312%3Cdef-alias--644-941--0-30251776781619%2Calias--433-684--0-1064308207794%3E%3E'
						},
						method: {
							type: 'string',
							const: 'PUT'
						}
					},
					required: [
						'body',
						'method'
					]
				}
			]
		},
		'RecursivePartial<alias-731470504-70254-70395-731470504-0-212312<def-alias--644-941--0-30251776781619,alias--433-684--0-1064308207794>>': {
			type: 'object',
			properties: {
				birthdate: {
					type: 'number'
				},
				name: {
					type: 'string',
					minLength: 1
				},
				email: {
					$ref: '#/definitions/EmailString'
				},
				description: {
					type: 'string'
				},
				icon: {
					$ref: '#/definitions/URLString'
				},
				site: {
					$ref: '#/definitions/URLString'
				},
				profileStyle: {
					type: 'string'
				},
				settings: {
					$ref: '#/definitions/RecursivePartial%3Cstructure--2379-3387--2368-3388--1794-3673--1766-3674--0-6872%3E'
				},
				nameColor: {
					type: 'string'
				}
			},
			additionalProperties: false
		},
		'EmailString': {
			type: 'string',
			description: 'The following regular expression is copied directly from https://html.spec.whatwg.org/multipage/input.html#valid-e-mail-address.',
			pattern: "^[a-zA-Z0-9.!#$%&'*+\\/=?^_`{|}~-]+@[a-zA-Z0-9](?:[a-zA-Z0-9-]{0,61}[a-zA-Z0-9])?(?:\\.[a-zA-Z0-9](?:[a-zA-Z0-9-]{0,61}[a-zA-Z0-9])?)*$"
		},
		'URLString': {
			type: 'string',
			pattern: '^https?://'
		},
		'RecursivePartial<structure--2379-3387--2368-3388--1794-3673--1766-3674--0-6872>': {
			type: 'object',
			properties: {
				emailPublic: {
					type: 'boolean'
				},
				favsPublic: {
					type: 'boolean'
				},
				ads: {
					$ref: '#/definitions/RecursivePartial%3Cstructure--2435-2486--2428-2487--2379-3387--2368-3388--1794-3673--1766-3674--0-6872%3E'
				},
				autoOpenSpoilers: {
					type: 'boolean'
				},
				preloadImages: {
					type: 'boolean',
					description: 'This makes images on adjacent pages always preload when a user visits a comic page.'
				},
				stickyNav: {
					type: 'boolean',
					description: 'This makes the nav bar always stay at the top of the screen when scrolling below it.'
				},
				imageSharpening: {
					type: 'boolean',
					description: 'This sets the image rendering style to nearest-neighbor on images which the user might want that on (such as comic panels).'
				},
				theme: {
					type: 'string',
					enum: [
						'standard',
						'dark',
						'felt',
						'sbahj',
						'trickster'
					]
				},
				style: {
					type: 'string'
				},
				controls: {
					$ref: '#/definitions/RecursivePartial%3Cstructure--2957-3026--2945-3027--2379-3387--2368-3388--1794-3673--1766-3674--0-6872%3E'
				},
				notifications: {
					$ref: '#/definitions/RecursivePartial%3Cstructure--3044-3384--3027-3384--2379-3387--2368-3388--1794-3673--1766-3674--0-6872%3E'
				}
			},
			additionalProperties: false
		},
		'RecursivePartial<structure--2435-2486--2428-2487--2379-3387--2368-3388--1794-3673--1766-3674--0-6872>': {
			type: 'object',
			properties: {
				side: {
					type: 'boolean'
				},
				matchedContent: {
					type: 'boolean'
				}
			},
			additionalProperties: false
		},
		'RecursivePartial<structure--2957-3026--2945-3027--2379-3387--2368-3388--1794-3673--1766-3674--0-6872>': {
			type: 'object',
			properties: {
				back: {
					type: 'string'
				},
				forward: {
					type: 'string'
				},
				toggleSpoilers: {
					type: 'string'
				}
			},
			additionalProperties: false
		},
		'RecursivePartial<structure--3044-3384--3027-3384--2379-3387--2368-3388--1794-3673--1766-3674--0-6872>': {
			type: 'object',
			properties: {
				messages: {
					$ref: '#/definitions/RecursivePartial%3CNotificationSetting%3E'
				},
				userTags: {
					$ref: '#/definitions/RecursivePartial%3CNotificationSetting%3E'
				},
				commentReplies: {
					$ref: '#/definitions/RecursivePartial%3CNotificationSetting%3E'
				},
				comicDefaults: {
					$ref: '#/definitions/RecursivePartial%3Cdef-alias--1276-1470--0-6872377513621%3E'
				},
				comics: {
					$ref: '#/definitions/RecursivePartial%3Cdef-alias--1470-1766--0-68722102184713%5B%5D%3E'
				}
			},
			additionalProperties: false
		},
		'RecursivePartial<NotificationSetting>': {
			type: 'object',
			properties: {
				email: {
					type: 'boolean'
				},
				site: {
					type: 'boolean'
				}
			},
			additionalProperties: false
		},
		'RecursivePartial<def-alias--1276-1470--0-6872377513621>': {
			type: 'object',
			additionalProperties: {
				$ref: '#/definitions/RecursivePartial%3CNotificationSetting%3E'
			}
		},
		'RecursivePartial<def-alias--1470-1766--0-68722102184713[]>': {
			type: 'array',
			items: {
				$ref: '#/definitions/RecursivePartial%3CComicNotificationSettings%3E'
			}
		},
		'RecursivePartial<ComicNotificationSettings>': {
			type: 'object',
			properties: {
				updates: {
					$ref: '#/definitions/RecursivePartial%3CNotificationSetting%3E'
				},
				news: {
					$ref: '#/definitions/RecursivePartial%3CNotificationSetting%3E'
				},
				comments: {
					$ref: '#/definitions/RecursivePartial%3C(undefined%7CNotificationSetting)%3E'
				}
			},
			additionalProperties: false
		},
		'RecursivePartial<(undefined|NotificationSetting)>': {
			type: 'object',
			properties: {
				email: {
					type: 'boolean'
				},
				site: {
					type: 'boolean'
				}
			},
			additionalProperties: false
		}
	}
});