// This file is automatically generated by `scripts/generate-validators`. Do not edit directly.

import { createValidator } from 'lib/server/api';

export default createValidator({
	$schema: 'http://json-schema.org/draft-07/schema#',
	$ref: '#/definitions/RequestMethod',
	definitions: {
		RequestMethod: {
			type: 'string',
			enum: [
				'GET',
				'DELETE',
				'PUT'
			]
		}
	}
}, {
	$schema: 'http://json-schema.org/draft-07/schema#',
	$ref: '#/definitions/Request',
	definitions: {
		'Request': {
			anyOf: [
				{
					type: 'object',
					additionalProperties: false,
					properties: {
						body: {},
						query: {
							type: 'object',
							properties: {
								userID: {
									type: 'string'
								}
							},
							required: [
								'userID'
							],
							additionalProperties: false
						},
						method: {
							type: 'string',
							const: 'GET'
						}
					},
					required: [
						'method',
						'query'
					]
				},
				{
					type: 'object',
					additionalProperties: false,
					properties: {
						body: {},
						query: {
							type: 'object',
							properties: {
								userID: {
									type: 'string'
								}
							},
							required: [
								'userID'
							],
							additionalProperties: false
						},
						method: {
							type: 'string',
							const: 'DELETE'
						}
					},
					required: [
						'method',
						'query'
					]
				},
				{
					type: 'object',
					additionalProperties: false,
					properties: {
						body: {
							$ref: '#/definitions/RecursivePartial%3Calias-2073358172-70263-70404-2073358172-0-212357%3Cdef-alias--789-1091--0-4720247327831%2Calias--719-953--0-3050652027738%3E%3E'
						},
						query: {
							type: 'object',
							properties: {
								userID: {
									type: 'string'
								}
							},
							required: [
								'userID'
							],
							additionalProperties: false
						},
						method: {
							type: 'string',
							const: 'PUT'
						}
					},
					required: [
						'body',
						'method',
						'query'
					]
				}
			]
		},
		'RecursivePartial<alias-2073358172-70263-70404-2073358172-0-212357<def-alias--789-1091--0-4720247327831,alias--719-953--0-3050652027738>>': {
			type: 'object',
			properties: {
				birthdate: {
					$ref: '#/definitions/DateNumber'
				},
				name: {
					type: 'string',
					minLength: 1,
					maxLength: 32
				},
				email: {
					$ref: '#/definitions/EmailString',
					description: 'The user\'s verified email address.'
				},
				description: {
					type: 'string',
					maxLength: 2000
				},
				icon: {
					anyOf: [
						{
							type: 'string',
							const: ''
						},
						{
							$ref: '#/definitions/URLString'
						}
					]
				},
				site: {
					anyOf: [
						{
							type: 'string',
							const: ''
						},
						{
							$ref: '#/definitions/URLString'
						}
					]
				},
				profileStyle: {
					type: 'string'
				},
				settings: {
					$ref: '#/definitions/RecursivePartial%3Cstructure--3249-4107--3238-4108--2265-4693--2128-4694--0-7953%3E'
				}
			},
			additionalProperties: false
		},
		'DateNumber': {
			$ref: '#/definitions/integer',
			minimum: -8640000000000000,
			maximum: 8640000000000000
		},
		'integer': {
			type: 'integer'
		},
		'EmailString': {
			type: 'string',
			pattern: '^[a-zA-Z0-9.!#$%&\'*+\\/=?^_`{|}~-]+@[a-zA-Z0-9](?:[a-zA-Z0-9-]{0,61}[a-zA-Z0-9])?(?:\\.[a-zA-Z0-9](?:[a-zA-Z0-9-]{0,61}[a-zA-Z0-9])?)*$'
		},
		'URLString': {
			type: 'string',
			pattern: '^https?://'
		},
		'RecursivePartial<structure--3249-4107--3238-4108--2265-4693--2128-4694--0-7953>': {
			type: 'object',
			properties: {
				emailPublic: {
					type: 'boolean'
				},
				birthdatePublic: {
					type: 'boolean'
				},
				favsPublic: {
					type: 'boolean'
				},
				autoOpenSpoilers: {
					type: 'boolean'
				},
				stickyNav: {
					type: 'boolean',
					description: 'This makes the nav bar always stay at the top of the screen when scrolling below it.'
				},
				imageAliasing: {
					type: 'boolean',
					description: 'This sets the image rendering style to nearest-neighbor on images which the user might want that on (such as story panels).'
				},
				theme: {
					$ref: '#/definitions/Theme'
				},
				style: {
					type: 'string'
				},
				controls: {
					$ref: '#/definitions/RecursivePartial%3Cstructure--3675-3744--3663-3745--3249-4107--3238-4108--2265-4693--2128-4694--0-7953%3E'
				},
				notifications: {
					$ref: '#/definitions/RecursivePartial%3Cstructure--3762-4104--3745-4104--3249-4107--3238-4108--2265-4693--2128-4694--0-7953%3E'
				}
			},
			additionalProperties: false
		},
		'Theme': {
			type: 'string',
			enum: [
				'standard',
				'dark',
				'felt',
				'sbahj',
				'trickster'
			]
		},
		'RecursivePartial<structure--3675-3744--3663-3745--3249-4107--3238-4108--2265-4693--2128-4694--0-7953>': {
			type: 'object',
			properties: {
				previousPage: {
					type: 'string'
				},
				nextPage: {
					type: 'string'
				},
				toggleSpoilers: {
					type: 'string'
				}
			},
			additionalProperties: false
		},
		'RecursivePartial<structure--3762-4104--3745-4104--3249-4107--3238-4108--2265-4693--2128-4694--0-7953>': {
			type: 'object',
			properties: {
				messages: {
					$ref: '#/definitions/RecursivePartial%3CNotificationSetting%3E'
				},
				userTags: {
					$ref: '#/definitions/RecursivePartial%3CNotificationSetting%3E'
				},
				commentReplies: {
					$ref: '#/definitions/RecursivePartial%3CNotificationSetting%3E'
				},
				storyDefaults: {
					$ref: '#/definitions/RecursivePartial%3Cdef-alias--1640-1832--0-79532047801771%3E'
				},
				stories: {
					type: 'array',
					items: {
						$ref: '#/definitions/StoryNotificationSettings'
					}
				}
			},
			additionalProperties: false
		},
		'RecursivePartial<NotificationSetting>': {
			type: 'object',
			properties: {
				email: {
					type: 'boolean'
				},
				site: {
					type: 'boolean'
				}
			},
			additionalProperties: false
		},
		'RecursivePartial<def-alias--1640-1832--0-79532047801771>': {
			type: 'object',
			additionalProperties: {
				$ref: '#/definitions/RecursivePartial%3CNotificationSetting%3E'
			}
		},
		'StoryNotificationSettings': {
			anyOf: [
				{
					type: 'boolean',
					const: true
				},
				{
					$ref: '#/definitions/StoryReaderNotificationSettings'
				},
				{
					$ref: '#/definitions/StoryEditorNotificationSettings'
				}
			],
			description: '`true` if the setting should inherit the user\'s default story notification settings.\n\n`StoryReaderNotificationSettings | StoryEditorNotificationSettings` otherwise.'
		},
		'StoryReaderNotificationSettings': {
			type: 'object',
			additionalProperties: false,
			properties: {
				comments: {
					not: {}
				},
				updates: {
					$ref: '#/definitions/NotificationSetting'
				},
				news: {
					$ref: '#/definitions/NotificationSetting'
				}
			},
			required: [
				'news',
				'updates'
			]
		},
		'NotificationSetting': {
			type: 'object',
			properties: {
				email: {
					type: 'boolean'
				},
				site: {
					type: 'boolean'
				}
			},
			required: [
				'email',
				'site'
			],
			additionalProperties: false
		},
		'StoryEditorNotificationSettings': {
			type: 'object',
			additionalProperties: {
				$ref: '#/definitions/NotificationSetting'
			}
		}
	}
});