// This file is automatically generated by `scripts/generate-validators`. Do not edit directly.

import createAPIValidator from 'lib/server/api/createAPIValidator';

export default createAPIValidator({
	$schema: 'http://json-schema.org/draft-07/schema#',
	$ref: '#/definitions/RequestMethod',
	definitions: {
		RequestMethod: {
			type: 'string',
			enum: [
				'GET',
				'DELETE',
				'PATCH'
			]
		}
	}
}, {
	$schema: 'http://json-schema.org/draft-07/schema#',
	$ref: '#/definitions/Request',
	definitions: {
		'Request': {
			anyOf: [
				{
					type: 'object',
					additionalProperties: false,
					properties: {
						body: {},
						query: {
							type: 'object',
							properties: {
								userID: {
									type: 'string'
								}
							},
							required: [
								'userID'
							],
							additionalProperties: false
						},
						method: {
							type: 'string',
							const: 'GET'
						}
					},
					required: [
						'method',
						'query'
					]
				},
				{
					type: 'object',
					additionalProperties: false,
					properties: {
						body: {},
						query: {
							type: 'object',
							properties: {
								userID: {
									type: 'string'
								}
							},
							required: [
								'userID'
							],
							additionalProperties: false
						},
						method: {
							type: 'string',
							const: 'DELETE'
						}
					},
					required: [
						'method',
						'query'
					]
				},
				{
					type: 'object',
					additionalProperties: false,
					properties: {
						body: {
							$ref: '#/definitions/RecursivePartial%3Calias-2073358172-73815-73956-2073358172-0-216469%3Cdef-alias-lib_client_users.ts-435-737-lib_client_users.ts-0-1306247327831%2Calias-1318184999-752-982-1318184999-0-30981551664714%3E%3E'
						},
						query: {
							type: 'object',
							properties: {
								userID: {
									type: 'string'
								}
							},
							required: [
								'userID'
							],
							additionalProperties: false
						},
						method: {
							type: 'string',
							const: 'PATCH'
						}
					},
					required: [
						'body',
						'method',
						'query'
					]
				},
				{
					not: {}
				}
			]
		},
		'RecursivePartial<alias-2073358172-73815-73956-2073358172-0-216469<def-alias-lib_client_users.ts-435-737-lib_client_users.ts-0-1306247327831,alias-1318184999-752-982-1318184999-0-30981551664714>>': {
			type: 'object',
			properties: {
				birthdate: {
					$ref: '#/definitions/DateNumber'
				},
				name: {
					type: 'string',
					minLength: 1,
					maxLength: 32
				},
				email: {
					$ref: '#/definitions/EmailString',
					description: 'The user\'s verified email address.'
				},
				description: {
					type: 'string',
					maxLength: 2000
				},
				icon: {
					anyOf: [
						{
							type: 'string',
							const: ''
						},
						{
							$ref: '#/definitions/URLString'
						}
					]
				},
				site: {
					anyOf: [
						{
							type: 'string',
							const: ''
						},
						{
							$ref: '#/definitions/URLString'
						}
					]
				},
				profileStyle: {
					type: 'string'
				},
				settings: {
					$ref: '#/definitions/RecursivePartial%3Cstructure-839751756-3290-4157-839751756-3279-4158-839751756-2318-4743-839751756-2181-4744-839751756-0-6751%3E'
				}
			},
			additionalProperties: false
		},
		'DateNumber': {
			$ref: '#/definitions/integer',
			minimum: -8640000000000000,
			maximum: 8640000000000000
		},
		'integer': {
			type: 'integer'
		},
		'EmailString': {
			type: 'string',
			pattern: '^[a-zA-Z0-9.!#$%&\'*+\\/=?^_`{|}~-]+@[a-zA-Z0-9](?:[a-zA-Z0-9-]{0,61}[a-zA-Z0-9])?(?:\\.[a-zA-Z0-9](?:[a-zA-Z0-9-]{0,61}[a-zA-Z0-9])?)*$'
		},
		'URLString': {
			type: 'string',
			pattern: '^https?://'
		},
		'RecursivePartial<structure-839751756-3290-4157-839751756-3279-4158-839751756-2318-4743-839751756-2181-4744-839751756-0-6751>': {
			type: 'object',
			properties: {
				emailPublic: {
					type: 'boolean'
				},
				birthdatePublic: {
					type: 'boolean'
				},
				favsPublic: {
					type: 'boolean'
				},
				autoOpenSpoilers: {
					type: 'boolean'
				},
				stickyNav: {
					type: 'boolean',
					description: 'This makes the nav bar always stay at the top of the screen when scrolling below it.'
				},
				imageAliasing: {
					type: 'boolean',
					description: 'This sets the image rendering style to nearest-neighbor on images which the user might want that on (such as story panels).'
				},
				theme: {
					$ref: '#/definitions/Theme'
				},
				style: {
					type: 'string'
				},
				controls: {
					$ref: '#/definitions/RecursivePartial%3Cstructure-839751756-3716-3794-839751756-3704-3795-839751756-3290-4157-839751756-3279-4158-839751756-2318-4743-839751756-2181-4744-839751756-0-6751%3E'
				},
				notifications: {
					$ref: '#/definitions/RecursivePartial%3Cstructure-839751756-3812-4154-839751756-3795-4154-839751756-3290-4157-839751756-3279-4158-839751756-2318-4743-839751756-2181-4744-839751756-0-6751%3E'
				}
			},
			additionalProperties: false
		},
		'Theme': {
			type: 'string',
			enum: [
				'standard',
				'dark',
				'felt',
				'sah'
			]
		},
		'RecursivePartial<structure-839751756-3716-3794-839751756-3704-3795-839751756-3290-4157-839751756-3279-4158-839751756-2318-4743-839751756-2181-4744-839751756-0-6751>': {
			type: 'object',
			properties: {
				previousPage: {
					type: 'string'
				},
				nextPage: {
					type: 'string'
				},
				toggleSpoilers: {
					type: 'string'
				}
			},
			additionalProperties: false
		},
		'RecursivePartial<structure-839751756-3812-4154-839751756-3795-4154-839751756-3290-4157-839751756-3279-4158-839751756-2318-4743-839751756-2181-4744-839751756-0-6751>': {
			type: 'object',
			properties: {
				messages: {
					$ref: '#/definitions/RecursivePartial%3CNotificationSetting%3E'
				},
				userTags: {
					$ref: '#/definitions/RecursivePartial%3CNotificationSetting%3E'
				},
				commentReplies: {
					$ref: '#/definitions/RecursivePartial%3CNotificationSetting%3E'
				},
				storyDefaults: {
					$ref: '#/definitions/RecursivePartial%3Cdef-alias-839751756-1693-1885-839751756-0-67512047801771%3E'
				},
				stories: {
					$ref: '#/definitions/RecursivePartial%3Cindexed-type-2073358172-74065-74088-2073358172-73956-74089-2073358172-0-216469%3Cdef-alias-1409642825-692-742-1409642825-0-62771012797994%2Cdef-alias-839751756-1885-2181-839751756-0-6751127147939%3E%3E'
				}
			},
			additionalProperties: false
		},
		'RecursivePartial<NotificationSetting>': {
			type: 'object',
			properties: {
				email: {
					type: 'boolean'
				},
				site: {
					type: 'boolean'
				}
			},
			additionalProperties: false
		},
		'RecursivePartial<def-alias-839751756-1693-1885-839751756-0-67512047801771>': {
			type: 'object',
			additionalProperties: {
				$ref: '#/definitions/RecursivePartial%3CNotificationSetting%3E'
			}
		},
		'RecursivePartial<indexed-type-2073358172-74065-74088-2073358172-73956-74089-2073358172-0-216469<def-alias-1409642825-692-742-1409642825-0-62771012797994,def-alias-839751756-1885-2181-839751756-0-6751127147939>>': {
			type: 'object',
			additionalProperties: {
				$ref: '#/definitions/RecursivePartial%3CStoryNotificationSettings%3E'
			}
		},
		'RecursivePartial<StoryNotificationSettings>': {
			type: 'object',
			properties: {
				updates: {
					$ref: '#/definitions/RecursivePartial%3CNotificationSetting%3E'
				},
				news: {
					$ref: '#/definitions/RecursivePartial%3CNotificationSetting%3E'
				},
				comments: {
					$ref: '#/definitions/RecursivePartial%3C(undefined%7CNotificationSetting)%3E'
				}
			},
			additionalProperties: false
		},
		'RecursivePartial<(undefined|NotificationSetting)>': {
			type: 'object',
			properties: {
				email: {
					type: 'boolean'
				},
				site: {
					type: 'boolean'
				}
			},
			additionalProperties: false
		}
	}
});
