// This file is automatically generated by `scripts/generate-validators`. Do not edit directly.

import createAPIValidator from 'lib/server/api/createAPIValidator';

export default createAPIValidator({
	$schema: 'http://json-schema.org/draft-07/schema#',
	$ref: '#/definitions/RequestMethod',
	definitions: {
		RequestMethod: {
			type: 'string',
			const: 'POST'
		}
	}
}, {
	$schema: 'http://json-schema.org/draft-07/schema#',
	$ref: '#/definitions/Request',
	definitions: {
		Request: {
			type: 'object',
			additionalProperties: false,
			properties: {
				body: {
					anyOf: [
						{
							type: 'object',
							additionalProperties: false,
							properties: {
								to: {
									type: 'array',
									items: {
										type: 'string'
									},
									minItems: 1,
									uniqueItems: true
								},
								subject: {
									type: 'string',
									minLength: 1,
									maxLength: 50
								},
								content: {
									type: 'string',
									minLength: 1,
									maxLength: 20000
								}
							},
							required: [
								'content',
								'subject',
								'to'
							]
						},
						{
							type: 'object',
							additionalProperties: false,
							properties: {
								replyTo: {
									type: 'string'
								},
								content: {
									type: 'string',
									minLength: 1,
									maxLength: 20000
								}
							},
							required: [
								'content',
								'replyTo'
							]
						}
					]
				},
				query: {},
				method: {
					type: 'string',
					const: 'POST'
				}
			},
			required: [
				'body',
				'method'
			]
		}
	}
});