// This file is automatically generated by `scripts/generate-validators`. Do not edit directly.

import { createValidator } from 'modules/server/api';

export default createValidator({
	$schema: 'http://json-schema.org/draft-07/schema#',
	$ref: '#/definitions/RequestMethod',
	definitions: {
		RequestMethod: {
			type: 'string',
			const: 'POST'
		}
	}
}, {
	$schema: 'http://json-schema.org/draft-07/schema#',
	$ref: '#/definitions/Request',
	definitions: {
		Request: {
			type: 'object',
			additionalProperties: false,
			properties: {
				body: {
					type: 'object',
					properties: {
						to: {
							type: 'array',
							items: {
								type: 'string'
							},
							minItems: 1,
							uniqueItems: true
						},
						subject: {
							type: 'string',
							minLength: 1,
							maxLength: 50
						},
						content: {
							type: 'string',
							minLength: 1,
							maxLength: 20000
						}
					},
					required: [
						'to',
						'subject',
						'content'
					],
					additionalProperties: false
				},
				query: {},
				method: {
					type: 'string',
					const: 'POST'
				}
			},
			required: [
				'body',
				'method'
			]
		}
	}
});