// This file is automatically generated by `scripts/generate-validators`. Do not edit directly.

import createAPIValidator from 'lib/server/api/createAPIValidator';

export default createAPIValidator({
	$schema: 'http://json-schema.org/draft-07/schema#',
	$ref: '#/definitions/RequestMethod',
	definitions: {
		RequestMethod: {
			type: 'string',
			const: 'PUT'
		}
	}
}, {
	$schema: 'http://json-schema.org/draft-07/schema#',
	$ref: '#/definitions/Request',
	definitions: {
		Request: {
			anyOf: [
				{
					type: 'object',
					additionalProperties: false,
					properties: {
						body: {
							anyOf: [
								{
									type: 'object',
									properties: {}
								},
								{
									type: 'object',
									properties: {}
								},
								{
									type: 'object',
									properties: {}
								}
							]
						},
						query: {
							type: 'object',
							properties: {
								storyID: {
									type: 'string'
								},
								pageID: {
									type: 'string'
								},
								commentID: {
									type: 'string'
								},
								userID: {
									type: 'string'
								}
							},
							required: [
								'storyID',
								'pageID',
								'commentID',
								'userID'
							],
							additionalProperties: false
						},
						method: {
							type: 'string',
							const: 'PUT'
						}
					},
					required: [
						'method',
						'query'
					]
				},
				{
					not: {}
				}
			]
		}
	}
});
