// This file is automatically generated by `scripts/generate-validators`. Do not edit directly.

import { createValidator } from 'lib/server/api';

export default createValidator({
	$schema: 'http://json-schema.org/draft-07/schema#',
	$ref: '#/definitions/RequestMethod',
	definitions: {
		RequestMethod: {
			type: 'string',
			const: 'GET'
		}
	}
}, {
	$schema: 'http://json-schema.org/draft-07/schema#',
	$ref: '#/definitions/Request',
	definitions: {
		Request: {
			type: 'object',
			additionalProperties: false,
			properties: {
				body: {},
				query: {
					type: 'object',
					properties: {
						storyID: {
							type: 'string'
						},
						limit: {
							anyOf: [
								{
									$ref: '#/definitions/integer'
								},
								{
									type: 'string'
								}
							],
							description: 'How many results to respond with.'
						},
						before: {
							type: 'string',
							description: 'Filter the results to only include news posted before the news post with this ID.'
						}
					},
					required: [
						'storyID'
					],
					additionalProperties: false
				},
				method: {
					type: 'string',
					const: 'GET'
				}
			},
			required: [
				'method',
				'query'
			]
		},
		integer: {
			type: 'integer'
		}
	}
});