// This file is automatically generated by `scripts/generate-validators`. Do not edit directly.

import { createValidator } from 'modules/server/api';

export default createValidator({
	$schema: 'http://json-schema.org/draft-07/schema#',
	$ref: '#/definitions/RequestMethod',
	definitions: {
		RequestMethod: {
			type: 'string',
			const: 'PUT'
		}
	}
}, {
	$schema: 'http://json-schema.org/draft-07/schema#',
	$ref: '#/definitions/Request',
	definitions: {
		'Request': {
			type: 'object',
			additionalProperties: false,
			properties: {
				body: {
					type: 'array',
					items: {
						anyOf: [
							{
								$ref: '#/definitions/ClientStoryPage'
							},
							{
								$ref: '#/definitions/RecursivePartial%3Calias-731470504-70254-70395-731470504-0-212312%3Cdef-alias--2198-2405--0-26561572850954%2Calias-ts-517-809-ts-0-29392145652127%3E%3E'
							}
						]
					},
					description: 'A record of `ClientStoryPage`s (some of which are partial) to add or change.'
				},
				query: {
					type: 'object',
					properties: {
						storyID: {
							type: 'string'
						}
					},
					required: [
						'storyID'
					],
					additionalProperties: false
				},
				method: {
					type: 'string',
					const: 'PUT'
				}
			},
			required: [
				'body',
				'method',
				'query'
			]
		},
		'ClientStoryPage': {
			type: 'object',
			additionalProperties: false,
			properties: {
				published: {
					type: 'number'
				},
				id: {
					$ref: '#/definitions/StoryPageID'
				},
				title: {
					type: 'string',
					maxLength: 500
				},
				content: {
					type: 'string'
				},
				nextPages: {
					type: 'array',
					items: {
						type: 'number'
					}
				},
				tags: {
					type: 'array',
					items: {
						$ref: '#/definitions/TagString'
					}
				},
				unlisted: {
					type: 'boolean'
				},
				disableControls: {
					type: 'boolean',
					description: 'Whether the client\'s controls should be disabled while this page is rendered.'
				},
				commentary: {
					type: 'string'
				},
				notify: {
					type: 'boolean',
					description: 'Whether this page was set to notify readers on publish.'
				}
			},
			required: [
				'commentary',
				'content',
				'disableControls',
				'id',
				'nextPages',
				'notify',
				'tags',
				'title',
				'unlisted'
			],
			description: 'A serializable version of `StoryPage` which only has properties that can safely be exposed to any client.'
		},
		'StoryPageID': {
			type: 'number',
			minimum: 1
		},
		'TagString': {
			type: 'string',
			minLength: 1,
			maxLength: 50,
			pattern: '^[a-z0-9](?:[a-z0-9-]*[a-z0-9])?$'
		},
		'RecursivePartial<alias-731470504-70254-70395-731470504-0-212312<def-alias--2198-2405--0-26561572850954,alias-ts-517-809-ts-0-29392145652127>>': {
			type: 'object',
			properties: {
				published: {
					type: 'number'
				},
				title: {
					type: 'string',
					maxLength: 500
				},
				content: {
					type: 'string'
				},
				nextPages: {
					type: 'array',
					items: {
						type: 'number'
					}
				},
				tags: {
					type: 'array',
					items: {
						$ref: '#/definitions/TagString'
					}
				},
				unlisted: {
					type: 'boolean'
				},
				disableControls: {
					type: 'boolean',
					description: 'Whether the client\'s controls should be disabled while this page is rendered.'
				},
				commentary: {
					type: 'string'
				},
				notify: {
					type: 'boolean',
					description: 'Whether this page was set to notify readers on publish.'
				}
			},
			additionalProperties: false
		}
	}
});