export const card: string;
export const code: string;
export const container: string;
export const description: string;
export const footer: string;
export const grid: string;
export const logo: string;
export const main: string;
export const title: string;